from collections.abc import Callable, Iterable
from typing import Any

import numpy
from dynesty import results
from matplotlib import figure

def runplot(
    results: results.Results,
    span: None | Iterable[tuple[float, float] | float] = None,
    logplot: bool = False,
    kde: bool = True,
    nkde: int = 1000,
    color: str | Iterable[str] = "blue",
    plot_kwargs: None | dict[str, Any] = None,
    label_kwargs: None | dict[str, Any] = None,
    lnz_error: bool = True,
    lnz_truth: None | float = None,
    truth_color: str | Iterable[str] = "red",
    truth_kwargs: None | dict[str, Any] = None,
    max_x_ticks: int = 8,
    max_y_ticks: int = 3,
    use_math_text: bool = True,
    mark_final_live: bool = True,
    fig: None | tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]] = None,
) -> tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]]: ...
def traceplot(
    results: results.Results,
    span: None | Iterable[tuple[float, float] | float] = None,
    quantiles: Iterable[float] = (0.025, 0.5, 0.975),
    smooth: float | Iterable[float] = 0.02,
    thin: int = 1,
    dims: None | Iterable[int] = None,
    post_color: str | Iterable[str] = "blue",
    post_kwargs: None | dict[str, Any] = None,
    kde: bool = True,
    nkde: int = 1000,
    trace_cmap: str | Iterable[str] = "plasma",
    trace_color: None | str | Iterable[str] = None,
    trace_kwargs: None | dict[str, Any] = None,
    connect: bool = False,
    connect_highlight: int | Iterable[int] = 10,
    connect_color: str = "red",
    connect_kwargs: None | dict[str, Any] = None,
    max_n_ticks: int = 5,
    use_math_text: bool = False,
    labels: None | Iterable[str] = None,
    label_kwargs: None | dict[str, Any] = None,
    show_titles: bool = False,
    title_quantiles: Iterable[float] = (0.025, 0.5, 0.975),
    title_fmt: str = ".2f",
    title_kwargs: None | dict[str, Any] = None,
    truths: None | Iterable[float] = None,
    truth_color: str | Iterable[str] = "red",
    truth_kwargs: None | dict[str, Any] = None,
    verbose: bool = False,
    fig: None | tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]] = None,
) -> tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]]: ...
def cornerpoints(
    results: results.Results,
    dims: None | Iterable[int] = None,
    thin: int = 1,
    span: None | Iterable[tuple[float, float] | float] = None,
    cmap: str = "plasma",
    color: None | str = None,
    kde: bool = True,
    nkde: int = 1000,
    plot_kwargs: None | dict[str, Any] = None,
    labels: None | Iterable[str] = None,
    label_kwargs: None | dict[str, Any] = None,
    truths: None | Iterable[float] = None,
    truth_color: str | Iterable[str] = "red",
    truth_kwargs: None | dict[str, Any] = None,
    max_n_ticks: int = 5,
    use_math_text: bool = False,
    fig: None | tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]] = None,
) -> tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]]: ...
def cornerplot(
    results: results.Results,
    dims: None | Iterable[int] = None,
    span: None | Iterable[tuple[float, float] | float] = None,
    quantiles: Iterable[float] = (0.025, 0.5, 0.975),
    color: str | Iterable[str] = "black",
    smooth: float | Iterable[float] = 0.02,
    quantiles_2d: None | Iterable[float] = None,
    hist_kwargs: None | dict[str, Any] = None,
    hist2d_kwargs: None | dict[str, Any] = None,
    labels: None | Iterable[str] = None,
    label_kwargs: None | dict[str, Any] = None,
    show_titles: bool = False,
    title_quantiles: Iterable[float] = (0.025, 0.5, 0.975),
    title_fmt: str = ".2f",
    title_kwargs: None | dict[str, Any] = None,
    truths: None | Iterable[float] = None,
    truth_color: str | Iterable[str] = "red",
    truth_kwargs: None | dict[str, Any] = None,
    max_n_ticks: int = 5,
    top_ticks: bool = False,
    use_math_text: bool = False,
    verbose: bool = False,
    fig: None | tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]] = None,
) -> tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]]: ...
def boundplot(
    results: results.Results,
    dims: tuple[int, int],
    it: None | int = None,
    idx: None | int = None,
    prior_transform: None
    | Callable[[numpy.typing.NDArray[numpy.floating]], numpy.typing.NDArray[numpy.floating]] = None,
    periodic: None | Iterable[int] = None,
    reflective: None | Iterable[int] = None,
    ndraws: int = 5000,
    color: str = "gray",
    plot_kwargs: None | dict[str, Any] = None,
    labels: None | Iterable[str] = None,
    label_kwargs: None | dict[str, Any] = None,
    max_n_ticks: int = 5,
    use_math_text: bool = False,
    show_live: bool = False,
    live_color: str = "darkviolet",
    live_kwargs: None | dict[str, Any] = None,
    span: None | Iterable[tuple[float, float]] = None,
    fig: None | tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]] = None,
) -> tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]]: ...
def cornerbound(
    results: results.Results,
    it: None | int = None,
    idx: None | int = None,
    dims: None | Iterable[int] = None,
    prior_transform: None
    | Callable[[numpy.typing.NDArray[numpy.floating]], numpy.typing.NDArray[numpy.floating]] = None,
    periodic: None | Iterable[int] = None,
    reflective: None | Iterable[int] = None,
    ndraws: int = 5000,
    color: str = "gray",
    plot_kwargs: None | dict[str, Any] = None,
    labels: None | Iterable[str] = None,
    label_kwargs: None | dict[str, Any] = None,
    max_n_ticks: int = 5,
    use_math_text: bool = False,
    show_live: bool = False,
    live_color: str = "darkviolet",
    live_kwargs: None | dict[str, Any] = None,
    span: None | Iterable[tuple[float, float]] = None,
    fig: None | tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]] = None,
) -> tuple[figure.Figure, numpy.typing.NDArray[numpy.object_]]: ...
